{
 "title": "AMD GPU v2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(hostname)" } },
   { "name": "gpu_id", "query": { "query": "label_values(gpu_id)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy GPU's",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(hostname) (gpu_health)", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Used VRAM %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum(gpu_used_vram / gpu_total_vram )",
     "legendFormat": "Used VRAM"
    },
    {
     "expr": "100*(1-sum(gpu_used_vram / gpu_total_vram ))",
     "legendFormat": "Available VRAM"
    }
   ]
  },
  {
   "title": "Used GTT %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum(gpu_used_gtt / gpu_total_gtt )",
     "legendFormat": "Used GTT"
    },
    {
     "expr": "100*(1-sum(gpu_used_gtt / gpu_total_gtt ))",
     "legendFormat": "Available GTT"
    }
   ]
  },
  {
   "title": "Host/GPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gpu_total_vram{hostname=\"$hostname\"})",
     "legendFormat": "VRAM"
    },
    {
     "expr": "max(gpu_total_gtt{hostname=\"$hostname\"})",
     "legendFormat": "GTT"
    }
   ]
  },
  {
   "title": "Used Memory %",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 * gpu_used_vram{hostname=\"$hostname\"} / gpu_total_vram{hostname=\"$hostname\"} )",
     "legendFormat": "VRAM"
    },
    {
     "expr": "avg(100 * gpu_used_gtt{hostname=\"$hostname\"} / gpu_total_gtt{hostname=\"$hostname\"})",
     "legendFormat": "GTT"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpu_used_vram{hostname=\"$hostname\"})",
     "legendFormat": "VRAM"
    },
    {
     "expr": "avg(gpu_used_gtt{hostname=\"$hostname\"})",
     "legendFormat": "GTT"
    }
   ]
  },
  {
   "title": "Used GTT Memory by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "gpu_used_gtt{hostname=\"$hostname\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Used VRAM Memory by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "gpu_used_vram{hostname=\"$hostname\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}