keys:
  - &framework_laptop age1l37eugsfaaetyr7l9zqj6usmg0xkvfnywvll73ml6jyy85u5ffjq85mg3g
  - &orangepi_zero3 age18nmkcrzuq3y204s6yvldczs790j9dr8tq577uzzu0syknjjjh3wqm588wq
creation_rules:
  - key_groups:
      - age:
          - *framework_laptop
          - *orangepi_zero3
        gcp_kms:
          # This resource is used to decrypt secrets in applications using a gcp service account
          - resource_id: projects/deep-contact-445917-i9/locations/us-central1/keyRings/sops-key-ring/cryptoKeys/sops-key
unencrypted_suffix: _unencrypted
mac: true
