customization:
  systemExtensions:
    officialExtensions:
      - siderolabs/amd-ucode
      - siderolabs/fuse3
      - siderolabs/xe
      - siderolabs/intel-ucode
      - siderolabs/mei
      - siderolabs/qemu-guest-agent
