network_10gb_nics: [eno7np2, eno8np3]
# Ceph config for proxmox
ceph_nvme_device: /dev/nvme0n1
ceph_partitions:
  - number: 1
    name: osd1_db
    start: 1GiB
    end: 101GiB # 100GiB for 1TB OSD DB
  - number: 2
    name: osd2_db
    start: 101GiB
    end: 495GiB # 384GiB for 3.84TB OSD DB
# Proxmox config
pve_ceph_osds:
  - device: /dev/sdb # 1 TB
    block.db: /dev/disk/by-id/nvme-Sabrent_Rocket_4.0_Plus_A5CD0712179183364499-part1
    crush.device.class: ssd
  - device: /dev/sdc # 3.84 TB
    block.db: /dev/disk/by-id/nvme-Sabrent_Rocket_4.0_Plus_A5CD0712179183364499-part3
    crush.device.class: ssd
