network_10gb_nics: [enp67s0f0, enp67s0f1]
# VM storage on freed consumer NVMe
storage_vm_device: /dev/disk/by-id/nvme-SHGP31-1000GM-2_AS0CN42841190CT25
# Ceph DB/WAL on new enterprise Intel NVMe
ceph_nvme_device: /dev/disk/by-id/nvme-INTEL_SSDPE21K015TA_PHKE0350002P1P5CGN
ceph_partitions:
  - number: 1
    name: osd1_db
    start: 1GiB
    end: 101GiB # 100 GiB for 1TB OSD
  - number: 2
    name: osd2_db
    start: 101GiB
    end: 201GiB # 100 GiB for 1TB OSD
  - number: 3
    name: osd3_db
    start: 201GiB
    end: 585GiB # 384 GiB for 3.5TB OSD
# Proxmox config
pve_ceph_osds:
  - device: /dev/sdd # 1TB (was sde before Micron removal)
    block.db: /dev/disk/by-id/nvme-INTEL_SSDPE21K015TA_PHKE0350002P1P5CGN-part1
    crush.device.class: ssd
  - device: /dev/sdc # 1TB Samsung 870 EVO
    block.db: /dev/disk/by-id/nvme-INTEL_SSDPE21K015TA_PHKE0350002P1P5CGN-part2
    crush.device.class: ssd
  - device: /dev/sdb # 3.5TB (was sdc before Micron removal)
    block.db: /dev/disk/by-id/nvme-INTEL_SSDPE21K015TA_PHKE0350002P1P5CGN-part3
    crush.device.class: ssd
pve_pcie_passthrough_enabled: true
pve_iommu_passthrough_mode: true
pve_iommu_unsafe_interrupts: false
pve_mediated_devices_enabled: false
pve_pcie_ovmf_enabled: true
pve_pci_device_ids:
  - id: "1002:7551" # AMD R9700
  - id: "1002:ab40" # AMD R9700 audio
  - id: "8086:56a6" # Intel Arc A310
  - id: "8086:4f92" # Intel Arc A310 audio
  - id: "8086:e223" # Intel Battlemage G21
  - id: "8086:e2f7" # Intel Battlemage G21 audio
  - id: "1b21:1064" # Sata device
  - id: "2116:2116" # Sata device
pve_vfio_blacklist_drivers:
  - name: "snd_hda_intel"
  - name: "i915"
  - name: "xe"
  - name: "amdgpu"
  - name: "radeon"
pve_pcie_ignore_msrs: false
pve_pcie_report_msrs: true
