apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: summit-sim
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: summit-sim
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/blake-hamm/summit-sim.git
    targetRevision: feature/gcp
    path: kubernetes
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
