site_name: bhamm-lab.com Docs
site_url: https://bhamm-lab.com/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - search
