- name: Ensure iommu=pt is added to GRUB_CMDLINE_LINUX_DEFAULT
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet"$'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet iommu=pt"'
    backup: true
  notify: Udate grub
- name: Ensure VFIO kernel modules are loaded at boot
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "{{ item }}"
    state: present
    create: true
    mode: '0644'
    owner: root
    group: root
  loop: "{{ proxmox_vfio_modules }}"
- name: Blacklist amdgpu driver
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist_amdgpu.conf
    line: "blacklist amdgpu"
    state: present
    create: true
    mode: '0644'
    owner: root
    group: root
- name: Configure VFIO PCI device binding
  ansible.builtin.copy:
    dest: /etc/modprobe.d/vfio.conf
    content: |
      options vfio-pci ids={{ proxmox_gpu_ids }}
      softdep radeon pre: vfio-pci
      softdep amdgpu pre: vfio-pci
      softdep snd_hda_intel pre: vfio-pci
    state: present
    create: true
    mode: '0644'
    owner: root
    group: root
  notify:
    - Update initramfs
    - Reboot system
