# tasks file for storage role
- name: Configure root drive
  ansible.builtin.include_tasks:
    file: root-drive.yml
- name: Configure swap
  ansible.builtin.include_tasks:
    file: swap.yml
  when: storage_resize_swap
- name: Create dedicated VM volume group
  ansible.builtin.include_tasks:
    file: local-vg.yml
  when: storage_vm_device | length > 0
- name: Extra config for Proxmox storage
  ansible.builtin.include_tasks:
    file: proxmox.yml
  when: "'proxmox' in group_names"
