proxmox_pbs: false
proxmox_reset_ceph: false
pve_ceph_rgw_enabled: false
nut_client_enabled: false
nut_server_host: ""
nut_ups_name: ""
nut_user: ""
# Ceph RGW Erasure Coding Configuration
pve_ceph_rgw_ec_k: 2
pve_ceph_rgw_ec_m: 1
pve_ceph_rgw_ec_failure_domain: host
pve_ceph_rgw_ec_plugin: isa
pve_ceph_rgw_ec_technique: reed_sol_van
pve_ceph_rgw_ec_profile_name: ec-2-1-profile
pve_ceph_rgw_ec_stripe_unit: 16384
pve_ceph_rgw_ec_pgs: 32
pve_ceph_rgw_non_ec_pgs: 32
# Ceph EC CephFS Configuration
pve_ceph_ecfs_enabled: false
pve_ceph_ecfs_name: cephfs_ec
pve_ceph_ecfs_storage_name: cephfs-ec
pve_ceph_ecfs_content: ["backup", "iso", "vztmpl", "snippets"]
pve_ceph_ecfs_ec_k: 2
pve_ceph_ecfs_ec_m: 1
pve_ceph_ecfs_ec_failure_domain: host
pve_ceph_ecfs_ec_plugin: isa
pve_ceph_ecfs_ec_technique: reed_sol_van
pve_ceph_ecfs_ec_profile_name: ec-2-1-profile
pve_ceph_ecfs_ec_stripe_unit: 16384
pve_ceph_ecfs_ec_pgs: 128
pve_ceph_ecfs_metadata_pgs: 32
pve_ceph_ecfs_backup_pgs: 32
