apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bin
    repoURL: https://github.com/metallb/metallb-operator.git
    targetRevision: v0.14.2
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: "CustomResourceDefinition"
      name: "bgppeers.metallb.io"
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  addresses:
    - 10.0.30.131-10.0.30.139 # Update in traefik values as well
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speaker-monitor
  namespace: metallb-system
  labels:
    component: speaker
    release: monitor
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  endpoints:
    - port: metricshttps
      interval: 30s
      honorLabels: true
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      scheme: "https"
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: "component"
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      name: speaker-monitor-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    argocd.argoproj.io/sync-wave: "4"
  labels:
    name: speaker-monitor-service
  name: speaker-monitor-service
  namespace: metallb-system
spec:
  selector:
    component: speaker
  clusterIP: None
  ports:
    - name: metricshttps
      port: 9120
      targetPort: 9120
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-monitor
  namespace: metallb-system
  labels:
    component: controller
    release: monitor
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  endpoints:
    - port: metricshttps
      interval: 30s
      honorLabels: true
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      scheme: "https"
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: "component"
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      name: controller-monitor-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    argocd.argoproj.io/sync-wave: "4"
  labels:
    name: controller-monitor-service
  name: controller-monitor-service
  namespace: metallb-system
spec:
  selector:
    component: controller
  clusterIP: None
  ports:
    - name: metricshttps
      port: 9120
      targetPort: 9120
  sessionAffinity: None
  type: ClusterIP
