- name: Downloading cilium CLI archive
  ansible.builtin.get_url:
    url: "{{ k3s_cilium_cli_url }}"
    dest: "/tmp/{{ k3s_cilium_cli_archive }}"
    checksum: "sha256:{{ k3s_cilium_cli_url }}.sha256sum"
    mode: "0600"
- name: Unarchive cilium CLI
  ansible.builtin.unarchive:
    src: "/tmp/{{ k3s_cilium_cli_archive }}"
    dest: "/tmp"
    remote_src: true
- name: Copy cilium cli binary to destination directory
  ansible.builtin.copy:
    src: "/tmp/cilium"
    dest: "/usr/local/bin/cilium"
    mode: "0755"
    owner: "root"
    group: "root"
    remote_src: true
- name: Check if Cilium is already installed and healthy
  ansible.builtin.command:
    cmd: cilium status --wait --wait-duration 45s
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  register: cilium_status_check
  ignore_errors: true
  changed_when: false
- name: Install Cilium CNI (only if not healthy)
  ansible.builtin.command:
    cmd: cilium install --version {{ k3s_cilium_version }} --set=ipam.operator.clusterPoolIPv4PodCIDRList="{{ k3s_server['cluster-cidr'] }}"
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  when: cilium_status_check is failed
  changed_when: false
