# Do not edit this file manually!  It is generated by Disko.
# You can customize this file by editing the Disko configuration at
# nix/hosts/orangepi/disko.nix

{
  # ... hardware configuration ...
}
