k8sServiceHost: '{{ k3s_server["tls-san"] }}'
k8sServicePort: '{{ k3s_server["listen-port"] }}'
kubeProxyReplacement: true
mtu: 9000
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - '{{ k3s_server["cluster-cidr"] }}'
      - '{{ k3s_server["service-cidr"] }}'
bpf:
  vlanBypass: [1, 20, 30]
routingMode: tunnel
# l2announcements:
#   enabled: true
# externalIPs:
#   enabled: true
k8sClientRateLimit:
  qps: 50
  burst: 200
operator:
  replicas: 1
  rollOutPods: true
  rollOutCiliumPods: true
# gatewayAPI:
#   enabled: true
envoy:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
prometheus:
  enabled: true
# securityContext:
#   capabilities:
#     keepCapNetBindService: true
debug:
  enabled: false
