collections:
  - name: community.hashi_vault
    version: "7.1.0"
  - name: devsec.hardening
    version: "10.5.2"
  - name: oxlorg.opnsense
    version: "25.7.8"
  - name: community.sops
    version: "2.2.7"
  - name: prometheus.prometheus
    version: "0.29.1"
  - name: grafana.grafana
    version: "6.1.0"
roles:
  - name: geerlingguy.ntp
    version: "4.0.0"
  - src: https://github.com/lae/ansible-role-proxmox.git
    name: lae.proxmox
    version: "v1.10.1"
