apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "26"
spec:
  destination:
    namespace: open-webui
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: open-webui
    repoURL: https://helm.openwebui.com
    targetRevision: 14.6.0
    helm:
      valuesObject:
        ollama:
          enabled: false
        ollamaUrls: []
        websocket:
          enabled: false
        pipelines:
          enabled: true
          extraEnvVars: []
        openaiBaseApiUrls:
          - "http://litellm.litellm.svc.cluster.local:4000/v1"
        strategy: {}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/db
            port: http
          failureThreshold: 2
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 20
        persistence:
          enabled: true
          existingClaim: "open-webui-data"
          provider: local
        extraEnvVars:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: open-webui-external-secret
                key: OPENAI_API_KEY
          - name: PIPELINES_API_KEY
            value: "0p3n-w3bu!"
          - name: OPENAI_API_KEYS
            value: "$(PIPELINES_API_KEY);$(OPENAI_API_KEY)"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: open-webui-postgresql-app
                key: uri
          - name: ENABLE_LOGIN_FORM
            value: "False"
          - name: WEBUI_URL
            value: "https://chat.bhamm-lab.com"
          - name: WEBUI_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: open-webui-external-secret
                key: WEBUI_SECRET_KEY
          - name: ENABLE_PASSWORD_AUTH
            value: "False"
          - name: DEFAULT_USER_ROLE
            value: "user"
          - name: ENABLE_WEB_SEARCH
            value: "True"
          - name: WEB_SEARCH_ENGINE
            value: "searxng"
          - name: WEB_SEARCH_RESULT_COUNT
            value: "3"
          - name: WEB_SEARCH_CONCURRENT_REQUESTS
            value: "1"
          - name: SEARXNG_QUERY_URL
            value: "http://searxng.searxng.svc.cluster.local:8080/search?q=<query>"
          - name: BYPASS_WEB_SEARCH_RESULT_LINK_SCRAPE
            value: "true"
        enableOpenaiApi: true
        sso:
          enabled: true
          enableSignup: true
          mergeAccountsByEmail: true
          enableRoleManagement: true
          enableGroupManagement: true
          oidc:
            enabled: true
            clientId: "open-webui"
            clientSecret: ""
            clientExistingSecret: "open-webui-external-secret"
            clientExistingSecretKey: "OAUTH_CLIENT_SECRET"
            providerUrl: "https://auth.bhamm-lab.com/.well-known/openid-configuration"
            providerName: "Authelia"
            scopes: "openid email profile groups"
          roleManagement:
            rolesClaim: "groups"
            allowedRoles: "user,admin"
            adminRoles: "admin"
          groupManagement:
            groupsClaim: "groups"
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
